[project]
authors = ["Luis Pedro Coelho <luis@luispedro.org>"]
channels = ["conda-forge", "bioconda"]
name = "ShortRead_mappings"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jug = ">=2.3.1,<3"
coverm = ">=0.7.0,<0.8"
